version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: laravel_app_dev
    container_name: aplanilha_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:delegated
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      DB_CONNECTION: pgsql
      DB_HOST: postgresql
      DB_PORT: 5432
      DB_DATABASE: aplanilha
      DB_USERNAME: aplanilha
      DB_PASSWORD: aplanilha
    networks:
      - app-network

  web:
    image: nginx:alpine
    container_name: aplanilha_web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-network

  postgresql:
    image: postgres:15-alpine
    container_name: aplanilha_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: aplanilha
      POSTGRES_USER: aplanilha
      POSTGRES_PASSWORD: aplanilha
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  node:
    image: node:20-alpine
    container_name: aplanilha_node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - node_modules:/var/www/html/node_modules
    command: sh -c "npm install --silent && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    depends_on:
      - app
    networks:
      - app-network

volumes:
  dbdata:
  node_modules:

networks:
  app-network:
    driver: bridge
